spring:
  datasource:
    username: root
    password: 1240023706
    url: jdbc:mysql://127.0.0.1:3306/school_helper?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      stat-view-servlet:
        allow: true
 
  redis:
    database: 0
    host: 192.168.137.134
    port: 6379
    password: 1240023706
    jedis:
      pool:
        max-active: 1000
        max-wait: -1
        max-idle: 10
        min-idle: 2
    timeout: 5000
  security:
    login-type: json
    browser:
      remember-time: 86400
      login-page: /login.html
      login-processing-url: /authentication/form
      no-login-processing-url: /authentication/require
mybatis:
  mapper-locations:
  - classpath*:mapper/**/*.xml
pagehelper:
  helper-dialect: mysql
  row-bounds-with-count: true
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
logging:
  config: classpath:logback-spring.xml

#fdfs:
#  connect-timeout: 600
#  so-timeout: 1500
#  web-server-url: http://192.168.106.140:8888/
#  tracker-list:
#  - 192.168.106.140:22122  
#  thumb-image:
#    height: 150 
#    width: 150
#  pool:
#    #从池中借出的对象的最大数目（配置为-1表示不限制）
#    max-total: -1
#    #获取连接时的最大等待毫秒数(默认配置为5秒)
#    max-wait-millis: 5000
    #每个key最大连接数
#    max-total-per-key: 50
    #每个key对应的连接池最大空闲连接数
#    max-idle-per-key: 10
    #每个key对应的连接池最小空闲连接数
#    max_idle_per_key: 5
wx:
  miniapp:
    configs:
        - appid: wx5a9d74cc2a8cca3f
          secret: b52a9c36333fa796001b34cb94ff4b8f
          token: #微信小程序消息服务器配置的token
          aesKey: #微信小程序消息服务器配置的EncodingAESKey
          msgDataFormat: JSON
